zope.exceptions-4.3-py2.7-nspkg.pth,sha256=SWEVH-jEWsKYrL0qoC6GBJaStx_iKxGoAY9PQycFVC4,529
zope.exceptions-4.3.dist-info/DESCRIPTION.rst,sha256=IsH5OfstjfSHcgqRZFXr-FnPgSd70iRSRd6RiKYOhRU,5961
zope.exceptions-4.3.dist-info/INSTALLER,sha256=zuuue4knoyJ-UwPPXg8fezS7VCrXJQrAP7zeNuwvFQg,4
zope.exceptions-4.3.dist-info/METADATA,sha256=MYarPA_sBkiD3j6AL37TMMaDbHp522hwV2CT1aWF2uI,7418
zope.exceptions-4.3.dist-info/RECORD,,
zope.exceptions-4.3.dist-info/WHEEL,sha256=o2k-Qa-RMNIJmUdIc7KU6VWR_ErNRbWNlxDIpl7lm34,110
zope.exceptions-4.3.dist-info/metadata.json,sha256=E7jM_ZSVOdAbOLwoJ4UcJ0zG7SZL_zMU4keaCXWup7E,1495
zope.exceptions-4.3.dist-info/namespace_packages.txt,sha256=QpUHvpO4wIuZDeEgKY8qZCtD-tAukB0fn_f6utzlb98,5
zope.exceptions-4.3.dist-info/top_level.txt,sha256=QpUHvpO4wIuZDeEgKY8qZCtD-tAukB0fn_f6utzlb98,5
zope/exceptions/__init__.py,sha256=s0KyaS4IBCRedMOscyDDKfBpR_aVUdR4O7gqx0t8xnI,1773
zope/exceptions/__pycache__/__init__.cpython-37.pyc,,
zope/exceptions/__pycache__/exceptionformatter.cpython-37.pyc,,
zope/exceptions/__pycache__/interfaces.cpython-37.pyc,,
zope/exceptions/__pycache__/log.cpython-37.pyc,,
zope/exceptions/exceptionformatter.py,sha256=RkqRvrObzMVZzUFsmKbrUx1jycf3-mODopjwoAPxbBU,11272
zope/exceptions/interfaces.py,sha256=0HJbxV-QQy8Ks-HU28hyxkUNzM2MEvw2ExsD8CTgTd4,3439
zope/exceptions/log.py,sha256=fBCO0uwQMVgXjQp_7Zir1qBFpRSUL7ilfemZfHYw0LY,1294
zope/exceptions/tests/__init__.py,sha256=MsSFjiLMLJZ7QhUPpVBWKiyDnCzryquRyr329NoCACI,2
zope/exceptions/tests/__pycache__/__init__.cpython-37.pyc,,
zope/exceptions/tests/__pycache__/test_exceptionformatter.cpython-37.pyc,,
zope/exceptions/tests/__pycache__/test_log.cpython-37.pyc,,
zope/exceptions/tests/test_exceptionformatter.py,sha256=4VouxPOP1Y-FYDgA-CIIzzjid3U7TqbIgZOLxTxoObY,33203
zope/exceptions/tests/test_log.py,sha256=zl1OGkSo-TPHPb-KvnThCev-qGKM_R5FfPbyVeDUNpg,3055
